version: '3.8'

services:
  satisfactory-ds-docker:
    build: .
    image: devidian/satisfactory-dedicated:latest
    container_name: satisfactory-ds-docker
    restart: unless-stopped
    volumes:
      # left side: your docker-host machine
      # right side: the paths in the image (!!do not change!!)
      - /appdata/satisfactoy/dedicated:/home/steam/Satisfactory-dedicated
    ports:
      - target: 15777
        published: 15777
        protocol: udp
        mode: host
      - target: 15000
        published: 15000
        protocol: udp
        mode: host
      - target: 7777
        published: 7777
        protocol: udp
        mode: host